import type {CorrectionProposals} from '../../core/correction/proposals.ts';
import { correctionContext, referenceLabels } from './reference.ts';
import type { TypeFile } from '../../core/config/project.ts';
import { activeUiCopy as c } from '../../core/ui/project-copy.ts';
export interface Revision {id:string;baseRevisionId:string|null;typeVersion:string;typeFile:TypeFile;displayNames:Record<string,string>;threshold:number;thresholdStatus:string;changeKind:string}
interface DefinitionState {actor:string;mode:string;canEdit:boolean;active:Revision|null;drafts:Revision[];seedTypeFile:TypeFile}
interface Options {request<T>(path:string,body?:unknown):Promise<T>;onError(error:unknown,host:HTMLElement):void;onActivated(revision:Revision):void}
const el=<K extends keyof HTMLElementTagNameMap>(tag:K,text?:string)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;return n;};
export async function categories(host:HTMLElement,options:Options):Promise<void>{
 const state=await options.request<DefinitionState>('/api/definitions');let draft=structuredClone(state.active?.typeFile??state.seedTypeFile),displayNames={...state.active?.displayNames};let saved:Revision|null=null;
 const heading=el('div');heading.className='page-intro';heading.append(el('h1',c.categoryTitle),el('p',c.categoryLede));host.append(heading);
 if(state.active?.thresholdStatus==='untested')host.append(el('p',c.categoriesUntested));if(state.active?.thresholdStatus==='unverified')host.append(el('p',c.categoriesUnverified));const status=el('div');status.setAttribute('role','status');const form=el('div');form.className='category-editor';const review=el('section');review.className='card';review.hidden=true;
 let suggestions:CorrectionProposals|null=null;const context=correctionContext();if(context){const correction=await options.request<{proposals:CorrectionProposals}>('/api/runs/'+encodeURIComponent(context.runId)+'/corrections/'+encodeURIComponent(context.correctionId));suggestions=correction.proposals;for(const type of correction.proposals.newTypes){if(type.id&&!draft.types.some(t=>t.id===type.id)){draft.types.push({id:type.id,name:type.name,what:'',not_for:'',examples:['']});displayNames[type.id]=type.name;}}}
 const editable=state.canEdit&&state.mode==='runtime';if(!editable){host.append(el('p',state.mode!=='runtime'?c.categoryGit:c.categoryReadOnly));const access=el('details');access.append(el('summary',c.categoryAccessDetails),el('p',c.categoryAccessHelp),el('p',c.categoryActor),el('pre',state.actor));host.append(access);}
 const act=(text:string,work:()=>void|Promise<void>)=>{const b=el('button',text);b.type='button';b.onclick=()=>{b.disabled=true;void Promise.resolve().then(work).catch(e=>options.onError(e,status)).finally(()=>{b.disabled=!editable;});};b.disabled=!editable;return b;};
 const input=(container:HTMLElement,label:string,value:string,change:(v:string)=>void,multiline=false)=>{const id=crypto.randomUUID(),l=el('label',label);l.htmlFor=id;const field=multiline?el('textarea'):el('input');field.id=id;field.value=value;field.disabled=!editable;if(field instanceof HTMLTextAreaElement)field.rows=3;field.oninput=()=>{change(field.value);saved=null;review.hidden=true;};container.append(l,field);return field;};
 function draw(){form.replaceChildren();draft.types.forEach((type,i)=>{const card=el('details');card.className='category-card';card.open=draft.types.length<5;const title=el('summary',displayNames[type.id]||type.name||c.categoryNew);card.append(title);const body=el('div');input(body,c.categoryDisplay,displayNames[type.id]??type.name,value=>{displayNames[type.id]=value;title.textContent=value||type.name;});input(body,c.categoryName,type.name,value=>type.name=value);input(body,c.categoryMeaning,type.what,value=>type.what=value,true);input(body,c.categoryExclusions,type.not_for,value=>type.not_for=value,true);input(body,c.categoryExamples,type.examples.join('\n'),value=>type.examples=value.split('\n'),true);const stable=el('details');stable.append(el('summary',c.categoryId),el('p',type.id));body.append(stable,act(c.categoryRemove,()=>{draft.types.splice(i,1);delete displayNames[type.id];saved=null;review.hidden=true;draw();}));card.append(body);form.append(card);});
 const none=el('details');none.append(el('summary',c.categoryNoneName));const body=el('div');input(body,c.categoryNoneName,draft.none_of_these.name,v=>draft.none_of_these.name=v);input(body,c.categoryNoneMeaning,draft.none_of_these.what,v=>draft.none_of_these.what=v,true);none.append(body);form.append(none);}
 const add=act(c.categoryAdd,()=>{const id='category_'+crypto.randomUUID().replaceAll('-','');draft.types.push({id,name:'',what:'',not_for:'',examples:['']});saved=null;review.hidden=true;draw();form.lastElementChild?.previousElementSibling?.scrollIntoView({block:'center'});});
 const save=act(c.categorySave,async()=>{status.replaceChildren(el('p',c.categorySaving));if(!draft.types.length)throw new Error(c.categoryEmpty);saved=await options.request<Revision>('/api/definitions/drafts',{baseRevisionId:state.active?.id??null,typeFile:draft,displayNames});status.replaceChildren(el('p',c.categoryDraftSaved));showReview(saved);});save.className='primary';
 function showReview(revision:Revision){review.hidden=false;review.replaceChildren(el('h2',c.categoryReview),el('p',c.categoryThreshold));const list=el('ul');revision.typeFile.types.forEach(t=>list.append(el('li',(revision.displayNames[t.id]||t.name)+': '+t.what)));review.append(list);const inherit=el('input');inherit.type='checkbox';const label=el('label');label.append(inherit,document.createTextNode(c.categoryInherit));review.append(label);const activate=act(c.categoryActivate,async()=>{status.replaceChildren(el('p',c.categoryActivating));const result=await options.request<{active:Revision}>('/api/definitions/'+encodeURIComponent(revision.id)+'/activate',{inheritThreshold:inherit.checked});state.active=result.active;review.hidden=true;status.replaceChildren(el('p',c.categoryActivated),el('p',result.active.thresholdStatus==='unverified'?c.categoriesUnverified:c.categoriesUntested));options.onActivated(result.active);});activate.className='primary';review.append(activate);}
 const actions=el('div');actions.className='actions';actions.append(add,save);host.append(form,actions,status,review);draw();
 if(suggestions){const suggestionsBox=el('details');suggestionsBox.append(el('summary',c.categorySuggestions),el('p',c.categorySuggestionHelp));const content=el('div');suggestionsBox.append(content);const candidates=[...suggestions.examples,...suggestions.newTypes.flatMap(type=>type.id?type.examples.map(example=>({...example,typeId:type.id!})):[])];let page=0;const candidateHost=el('div'),navigation=el('div'),previous=act(c.previousPage,()=>{page--;drawSuggestions();}),next=act(c.nextPage,()=>{page++;drawSuggestions();}),count=el('span');navigation.className='table-tools';navigation.append(previous,count,next);content.append(candidateHost,navigation);function drawSuggestions(){candidateHost.replaceChildren();candidates.slice(page*10,page*10+10).forEach(candidate=>{const item=el('details');item.append(el('summary',candidate.title));const excerpt=candidate.digestLines.length?candidate.digestLines.join('\n'):candidate.readerEvidence?.map(e=>e.quote).join('\n')??'';item.append(el('pre',excerpt));if(excerpt)item.append(act(c.categoryUseExample,()=>{const type=draft.types.find(t=>t.id===candidate.typeId);if(!type)return;type.examples=[...type.examples.filter(x=>x.trim()),excerpt];saved=null;review.hidden=true;draw();status.replaceChildren(el('p',c.categoryExampleAdded));}));candidateHost.append(item);});previous.disabled=page===0;next.disabled=(page+1)*10>=candidates.length;count.textContent=c.pageCount(candidates.length?page*10+1:0,Math.min((page+1)*10,candidates.length),candidates.length);}drawSuggestions();for(const exclusion of suggestions.notFor){const item=el('details');item.append(el('summary',exclusion.fromType),el('p',exclusion.candidate),act(c.categoryUseExclusion,()=>{const type=draft.types.find(t=>t.id===exclusion.fromType);if(!type)return;type.not_for=type.not_for+' '+exclusion.candidate;saved=null;review.hidden=true;draw();status.replaceChildren(el('p',c.categoryExclusionAdded));}));content.append(item);}host.append(suggestionsBox);}
 if(state.active&&context){const reference=el('details');reference.append(el('summary',c.referenceTitle));const body=el('div');reference.append(body);host.append(reference);let loaded=false;reference.ontoggle=()=>{if(reference.open&&!loaded){loaded=true;void referenceLabels(body,state.active!,{...options,onReady:()=>{localStorage.setItem('local-extraction-run',crypto.randomUUID());location.hash='home';}}).catch(error=>{loaded=false;options.onError(error,body);});}};}
 if(state.drafts.length){const prior=el('details');prior.append(el('summary',c.categoryDrafts));state.drafts.forEach(item=>{const b=act(c.categoryOpenDraft+' · '+item.id.slice(0,8),()=>{draft=structuredClone(item.typeFile);displayNames={...item.displayNames};saved=item;draw();showReview(item);});prior.append(b);});host.append(prior);}
}
