import {activeUiCopy as c} from '../../core/ui/project-copy.ts';
import type {Revision} from './categories.ts';
interface Candidate {fingerprint:string;originalFilename:string;correctedFolder:string|null;previousFolder:string;previousRule:string;moved:boolean;status:string;labels:string[]}
interface Correction {referenceCandidates:Candidate[];proposals:{newTypes:{id:string|null;name:string;folder:string}[]}}
interface Options {request<T>(path:string,body?:unknown):Promise<T>;onError(error:unknown,host:HTMLElement):void;onReady():void}
const el=<K extends keyof HTMLElementTagNameMap>(tag:K,text?:string)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;return n;};
export function correctionContext():{runId:string;correctionId:string}|null {const raw=localStorage.getItem('workspace-correction');if(!raw)return null;const value=JSON.parse(raw);return typeof value.runId==='string'&&typeof value.correctionId==='string'?value:null;}
export async function referenceLabels(host:HTMLElement,revision:Revision,options:Options):Promise<void>{
 const context=correctionContext();if(!context)return;const path='/api/runs/'+encodeURIComponent(context.runId)+'/corrections/'+encodeURIComponent(context.correctionId),source=await options.request<Correction>(path);let page=0;const opened=new Set<string>();const edits=new Map<string,{fingerprint:string;status:string;labels:string[]}>(),folderLabels:Record<string,string>={};
 const box=el('section');box.className='card reference-labels';box.append(el('h2',c.referenceTitle),el('p',c.referenceHelp));const status=el('div');status.setAttribute('role','status');
 const select=(label:string,choices:[string,string][],value:string,onChange:(v:string)=>void)=>{const l=el('label',label),s=el('select');s.id=crypto.randomUUID();l.htmlFor=s.id;choices.forEach(([id,name])=>{const o=el('option',name);o.value=id;s.append(o);});s.value=value;s.onchange=()=>onChange(s.value);const w=el('div');w.append(l,s);return w;};
 const choices:[string,string][]=[['',c.chooseDecision],...revision.typeFile.types.map(t=>[t.id,revision.displayNames[t.id]||t.name] as [string,string])];
 for(const folder of new Set(source.referenceCandidates.filter(x=>x.correctedFolder&&!choices.some(([id])=>id===x.correctedFolder)&&x.status!=='excluded'&&x.status!=='failure').map(x=>x.correctedFolder!))){box.append(select(c.referenceFolder+' · '+folder,choices,'',v=>{if(v)folderLabels[folder]=v;else delete folderLabels[folder];draw();}));}
 const warning=el('div'),acknowledge=el('input');acknowledge.type='checkbox';const acknowledgeLabel=el('label');acknowledgeLabel.append(acknowledge,document.createTextNode(c.referenceAllowUnconfirmed));const warningText=el('p');warning.append(warningText,acknowledgeLabel);box.append(warning);function unconfirmed(){return source.referenceCandidates.filter(item=>{const edit=edits.get(item.fingerprint);return edit?edit.status==='unconfirmed':item.status==='unconfirmed'&&!folderLabels[item.correctedFolder??''];}).length;}
 const search=el('input');search.type='search';search.placeholder=c.searchDocuments;search.setAttribute('aria-label',c.searchDocuments);search.oninput=()=>{page=0;draw();};box.append(search);const rows=el('div'),paging=el('div');paging.className='table-tools';const prev=el('button',c.previousPage),next=el('button',c.nextPage),count=el('span');prev.onclick=()=>{page--;draw();};next.onclick=()=>{page++;draw();};paging.append(prev,count,next);box.append(rows,paging);
 function draw(){const remaining=unconfirmed();warning.hidden=remaining===0;warningText.textContent=c.referenceUnconfirmedCount(remaining);acknowledge.checked=false;const filtered=source.referenceCandidates.filter(x=>x.originalFilename.toLowerCase().includes(search.value.toLowerCase()));page=Math.max(0,Math.min(page,Math.ceil(filtered.length/10)-1));rows.replaceChildren();filtered.slice(page*10,page*10+10).forEach(item=>{const row=el('details');row.open=opened.has(item.fingerprint);row.ontoggle=()=>{if(row.open)opened.add(item.fingerprint);else opened.delete(item.fingerprint);};row.append(el('summary',item.originalFilename));const body=el('div');const selected=edits.get(item.fingerprint)??{fingerprint:item.fingerprint,status:folderLabels[item.correctedFolder??'']?'label':item.status,labels:folderLabels[item.correctedFolder??'']?[folderLabels[item.correctedFolder!]]:[...item.labels]};row.append(el('p',selected.status==='ambiguous'?c.referenceAmbiguous:selected.labels.map(id=>choices.find(x=>x[0]===id)?.[1]??id).join(' / ')||selected.status));
 if(item.status==='failure'){body.append(el('p',c.referenceFailure));row.append(body);rows.append(row);return;}
 const store=()=>edits.set(item.fingerprint,{...selected,labels:[...selected.labels]});body.append(select(c.referenceStatus,[...(item.status==='unconfirmed'?[['unconfirmed',c.referenceUnconfirmed] as [string,string]]:[]),['label',c.referenceLabel],['ambiguous',c.referenceAmbiguous],['excluded',c.referenceExcluded]],selected.status,v=>{selected.status=v;if(v==='unconfirmed'){edits.delete(item.fingerprint);draw();return;}if(v==='excluded')selected.labels=[];else if(v==='label')selected.labels=selected.labels.slice(0,1);store();draw();}));
 if(selected.status==='label'||selected.status==='ambiguous'){body.append(select(c.referenceFirst,choices,selected.labels[0]??'',v=>{selected.labels[0]=v;store();}));if(selected.status==='ambiguous')body.append(select(c.referenceSecond,choices,selected.labels[1]??'',v=>{selected.labels[1]=v;store();}));}
 row.append(body);rows.append(row);});count.textContent=c.pageCount(filtered.length?page*10+1:0,Math.min((page+1)*10,filtered.length),filtered.length);prev.disabled=page===0;next.disabled=(page+1)*10>=filtered.length;}
 const save=el('button',c.referenceSave);save.className='primary';save.onclick=()=>{if(unconfirmed()&&!acknowledge.checked){acknowledge.focus();return;}if([...edits.values()].some(item=>item.status==='ambiguous'&&(item.labels.length<2||item.labels.some(x=>!x)||new Set(item.labels).size!==item.labels.length)||item.status==='label'&&(item.labels.length!==1||!item.labels[0]))){options.onError(new Error(c.referenceInvalidPair),status);return;}save.disabled=true;status.replaceChildren(el('p',c.referenceSaving));void options.request<{id:string}>(path+'/reference',{definitionRevisionId:revision.id,folderLabels,labels:[...edits.values()]}).then(result=>{localStorage.setItem('workspace-reference',result.id);sessionStorage.setItem('workspace-reference',result.id);status.replaceChildren(el('p',c.referenceSaved));const start=el('button',c.chooseFollowupFiles);start.className='primary';start.onclick=options.onReady;status.append(start);}).catch(error=>options.onError(error,status)).finally(()=>save.disabled=false);};box.append(save,status);host.append(box);draw();
}
export async function showComparison(host:HTMLElement,runId:string,request:Options['request']):Promise<void>{
 const result=await request<{comparison:null|{complete:boolean;moved:{matched:number;comparable:number;total:number};previouslyFiled:{same:number;comparable:number;total:number};missing:number;ambiguous:number;excluded:number;failures:number;newDocuments:number;unconfirmed:number;sourceFailures:number}}|null>('/api/runs/'+encodeURIComponent(runId)+'/comparison');const value=result&&'comparison'in result?result.comparison:result as unknown as NonNullable<NonNullable<typeof result>['comparison']>;if(!value)return;
 const box=el('section');box.className='card comparison-card';box.append(el('h2',c.comparisonTitle));if(!value.complete)box.append(el('p',c.comparisonProvisional));const stats=el('div');stats.className='stats';for(const [label,number]of [[c.comparisonMoved,`${value.moved.matched} / ${value.moved.comparable}`],[c.comparisonFiled,`${value.previouslyFiled.same} / ${value.previouslyFiled.comparable}`]]){const item=el('div');item.className='stat';item.append(el('span',label),el('strong',number));stats.append(item);}box.append(stats,el('p',`${c.comparisonMoved}: ${value.moved.comparable} ${c.comparisonEligible}; ${value.moved.total} ${c.comparisonGroupTotal}. ${c.comparisonFiled}: ${value.previouslyFiled.comparable} ${c.comparisonEligible}; ${value.previouslyFiled.total} ${c.comparisonGroupTotal}.`));const list=el('p');list.textContent=[[c.comparisonMissing,value.missing],[c.comparisonAmbiguous,value.ambiguous],[c.comparisonExcluded,value.excluded],[c.comparisonFailures,value.failures+value.sourceFailures],[c.comparisonUnconfirmed,value.unconfirmed],[c.comparisonNew,value.newDocuments]].map(([name,n])=>`${name}: ${n}`).join(' · ');box.append(list);host.append(box);
}
