import test from 'node:test';import assert from 'node:assert/strict';import {Runner} from './execution.ts';import {authorizeRunBudget} from '../cost/run-budget.ts';import type {WorkflowStep} from 'cloudflare:workers';import type {RunRow} from './store.ts';
function setup(){
 let time=0,deadline=1000,insideStep=false,prior=false,kill=false,spend='0';const sleeps:{name:string;until:number}[]=[],plans:string[]=[],saved=new Map<string,unknown>();
 const budget=authorizeRunBudget({mode:'limited',limits:{blended:'100',openai:null,typesafe:null},unlimitedAcknowledged:false},'test','2026-09-22');const run={id:'run',status:'running',budget_json:JSON.stringify(budget)} as RunRow;
 const env={MODEL_CALLS_ENABLED:'true',DB:{prepare:(sql:string)=>({bind(){return this;},first:async()=>sql.includes('FROM checkpoints')?(prior?{status:'complete'}:null):sql.includes('FROM provider_cooldowns')?{until_ms:deadline}:sql.includes('FROM controls')?{kill:kill?1:0}:{count:0}})}} as unknown as Env;
 const step={sleepUntil:async(name:string,until:number)=>{assert.equal(insideStep,false);sleeps.push({name,until});time=until;}} as unknown as WorkflowStep;const runner=new Runner(env,run,'fingerprint',step);runner.store.run=async()=>run;runner.store.spendByVendor=async()=>({blended:spend,openai:spend,typesafe:'0'});runner.store.event=async()=>{};runner.stage=async(name,action)=>{insideStep=true;plans.push(name);try{saved.set(name,await action());return name;}finally{insideStep=false;}};
 runner.store.json=async<T>(key:string)=>saved.get(key) as T;
 return{runner,sleeps,plans,step,now:()=>time,setDeadline:(v:number)=>{deadline=v;},setPrior:()=>{prior=true;},kill:()=>{kill=true;},spend:()=>{spend='100';}};
}
test('Runner admission sleeps only top-level at stable absolute deadline and does not cache an admitted grant',async()=>{const h=setup(),now=Date.now;Date.now=h.now;try{await h.runner.admission('reader',1);assert.deepEqual(h.sleeps,[{name:'reader-admission-1-1000-wait',until:1000}]);h.setDeadline(2000);await h.runner.admission('reader',1);assert.equal(h.sleeps[1].until,2000);h.setPrior();h.setDeadline(3000);await h.runner.admission('reader',1);assert.equal(h.sleeps.length,2);}finally{Date.now=now;}});
test('Runner rechecks actual kill and budget guards after admission sleep',async()=>{for(const reason of ['kill','spend'] as const){const h=setup(),now=Date.now;Date.now=h.now;const originalSleep=h.step.sleepUntil;h.step.sleepUntil=async(name,until)=>{await originalSleep.call(h.step,name,until);h[reason]();};try{await assert.rejects(h.runner.admission('reader',1),{code:reason==='kill'?'E_KILL_SWITCH':'E_LIVE_BUDGET'});assert.equal(h.plans.length,2);}finally{Date.now=now;}}});
