import test from 'node:test';import assert from 'node:assert/strict';import {correctionContext} from './correction-context.ts';
test('deleted and source-containing artifacts are never read, even with retained reader evidence',async()=>{
 for(const state of [{deleted:true,containsText:false},{deleted:false,containsText:true}]){
 const reads:string[]=[];const quote='  Exact\nquote  ';const result=await correctionContext('original.docx','source',{metadata:async key=>key==='source'?state:{deleted:false,containsText:false},read:async()=>{throw Error('Source read forbidden');},readReader:async key=>{reads.push(key);return{model:'model',verdicts:[{type_id:'type_a',is_type:false,rationale:'Reason',evidence:[quote],closest_alternative:null}]};}},'reader');
 assert.deepEqual(reads,['reader']);assert.equal(result.title,'original.docx');assert.deepEqual(result.digestLines,[]);assert.equal(result.fullContextUnavailable,true);assert.deepEqual(result.readerEvidence,[{typeId:'type_a',isType:false,quote,verdictIndex:0,quoteIndex:0,artifactKey:'reader'}]);
 }
});
test('deleted or source-marked reader artifact is not read as retained evidence',async()=>{for(const state of [{deleted:true,containsText:false},{deleted:false,containsText:true}]){const result=await correctionContext('original.docx',null,{metadata:async()=>state,read:async()=>{throw Error('Forbidden');},readReader:async()=>{throw Error('Forbidden');}},'reader');assert.deepEqual(result.readerEvidence,[]);assert.equal(result.unavailable,true);}});
test('legacy retained digest context remains exact',async()=>{const result=await correctionContext('original.docx','legacy',{metadata:async()=>({deleted:false,containsText:false}),read:async()=>({policyVersion:'named-fields-json-v1',state:{title:'retained',sections:[{text:' excerpt '}]}})});assert.equal(result.title,'retained');assert.deepEqual(result.digestLines,[' excerpt ']);assert.equal(result.unavailable,false);});
test('reader evidence preserves every verdict, duplicate quote and original ordering',async()=>{const result=await correctionContext('f',null,{metadata:async()=>({deleted:false,containsText:false}),read:async()=>{throw Error('Forbidden');},readReader:async()=>({model:'m',verdicts:[{type_id:'a',is_type:true,rationale:'r',evidence:['same','same'],closest_alternative:null},{type_id:'b',is_type:false,rationale:'r',evidence:[' x '],closest_alternative:null}]})},'reader');assert.deepEqual(result.readerEvidence.map(q=>[q.typeId,q.isType,q.quote,q.verdictIndex,q.quoteIndex]),[['a',true,'same',0,0],['a',true,'same',0,1],['b',false,' x ',1,0]]);});
