import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync,type SQLInputValue} from 'node:sqlite';
import {readFileSync} from 'node:fs';
import {Store} from './store.ts';
import {recoverRun,inspectRunRecovery,dispatchRecovery,canOfferRecovery} from './run-recovery.ts';
function setup(){
 const db=new DatabaseSync(':memory:');for(const file of ['0001_initial.sql','0003_extraction_metadata.sql','0008_run_recovery.sql','0009_recovery_dispatch_fence.sql'])db.exec(readFileSync('migrations/'+file,'utf8'));
 db.prepare('INSERT INTO quotes VALUES(?,?,?,?,?,?,?,?)').run('q','owner','then','interactive','types','hash','{}','{}');
 db.prepare("INSERT INTO runs(id,actor,status,created_at,mode,expected_count,threshold,threshold_justification,type_version,pack_json,budget_json,quote_id,halt_json) VALUES('run','owner','halted','then','interactive',2,.9,'original','types','frozen','budget','q',?)").run(JSON.stringify({code:'E_WORKFLOW_INTERRUPTED'}));
 for(const [fingerprint,status] of [['finished','complete'],['pending','running']])db.prepare('INSERT INTO documents(run_id,fingerprint,tag,original_filename,status,input_key,input_hash,workflow_id) VALUES(?,?,?,?,?,?,?,?)').run('run',fingerprint,fingerprint,'original',status,`input-${fingerprint}`,'hash',`old-${fingerprint}`);
 db.prepare("INSERT INTO artifacts(key,run_id,kind,contains_text,created_at,state) VALUES('paid','run','raw',0,'then','complete')").run();
 db.prepare("INSERT INTO checkpoints(run_id,fingerprint,name,status,artifact_key,started_at) VALUES('run','pending','confidence-http-1','complete','paid','then')").run();
 db.prepare("INSERT INTO vendor_calls(attempt_id,run_id,fingerprint,role,model_requested,latency_ms,raw_key,created_at,cost_nano) VALUES('run-pending-confidence-1','run','pending','confidence','pin',1,'paid','then','100')").run();
 const statuses=new Map([['old-finished','complete'],['old-pending','errored']]);const created:string[]=[],lookups:string[]=[];const lookupErrors:Error[]=[];let loseAck=false,lookupFails=false;
 const prepare=(sql:string)=>{let args:SQLInputValue[]=[];return{bind(...values:SQLInputValue[]){args=values;return this;},async first(){return db.prepare(sql).get(...args)??null;},async all(){return{results:db.prepare(sql).all(...args)};},async run(){return{meta:{changes:Number(db.prepare(sql).run(...args).changes)}};}};};
 const env={DB:{prepare,async batch(statements:Array<{run():Promise<unknown>}>){db.exec('BEGIN');try{const result=[];for(const statement of statements)result.push(await statement.run());db.exec('COMMIT');return result;}catch(error){db.exec('ROLLBACK');throw error;}}},ARTIFACTS:{head:async()=>({})},DOCUMENT_WORKFLOW:{async get(id:string){lookups.push(id);return{async status(){if(lookupErrors.length)throw lookupErrors.shift();if(lookupFails||!statuses.has(id))throw new Error('unverified');return{status:statuses.get(id)};}};},async create(options:{id:string}){created.push(options.id);statuses.set(options.id,'queued');if(loseAck)throw new Error('lost acknowledgement');}}} as unknown as Env;
 return{db,store:new Store(env),statuses,created,lookups,lookupErrors,options:{acknowledged:true,assertReady:async()=>{}},loseAck:()=>{loseAck=true;},lookupFails:()=>{lookupFails=true;}};
}
test('explicit recovery keeps frozen run, paid checkpoints and old execution history; skips completed documents',async()=>{const f=setup();try{const checkpoint=f.db.prepare('SELECT * FROM checkpoints').all();const result=await recoverRun(f.store,'run','owner',f.options);assert.equal(result.pending,0);assert.equal(f.created.length,1);assert.equal(f.db.prepare("SELECT workflow_id FROM documents WHERE fingerprint='finished'").get()!.workflow_id,'old-finished');assert.deepEqual(f.db.prepare('SELECT * FROM checkpoints').all(),checkpoint);assert.equal(f.db.prepare('SELECT pack_json FROM runs').get()!.pack_json,'frozen');assert.equal(f.statuses.get('old-pending'),'errored');await dispatchRecovery(f.store,'run','owner',f.options);assert.equal(f.created.length,1);}finally{f.db.close();}});
test('lost creation acknowledgement reconciles reserved identity without another create',async()=>{const f=setup();try{f.loseAck();await recoverRun(f.store,'run','owner',f.options);await recoverRun(f.store,'run','owner',f.options);assert.equal(f.created.length,1);}finally{f.db.close();}});
test('unsafe state and unauthorized callers never dispatch or activate',async()=>{for(const change of ['owner','ack','ready','running-checkpoint','failed-checkpoint','writing','nonterminal','unknown-status','missing-input','batch','unknown-cost']){const f=setup();try{
 let actor='owner';if(change==='owner')actor='other';if(change==='ack')f.options.acknowledged=false;if(change==='ready')f.options.assertReady=async()=>{throw new Error('kill or budget blocked');};
 if(change==='running-checkpoint'||change==='failed-checkpoint')f.db.prepare('UPDATE checkpoints SET status=?').run(change.split('-')[0]);
 if(change==='writing')f.db.prepare("UPDATE artifacts SET state='writing'").run();if(change==='nonterminal')f.statuses.set('old-pending','waiting');if(change==='unknown-status')f.lookupFails();if(change==='missing-input')f.db.prepare("UPDATE documents SET input_key=NULL WHERE fingerprint='pending'").run();
 if(change==='batch')f.db.prepare("INSERT INTO batch_jobs(id,run_id,fingerprint,schema_attempt,state) VALUES('b','run','pending',1,'submitted')").run();
 if(change==='unknown-cost')f.db.prepare("INSERT INTO vendor_calls(attempt_id,run_id,fingerprint,role,model_requested,latency_ms,raw_key,created_at) VALUES('attempt','run','pending','confidence','pin',1,'paid','then')").run();
 await assert.rejects(()=>recoverRun(f.store,'run',actor,f.options),change);assert.equal(f.created.length,0,change);assert.equal(f.db.prepare('SELECT status FROM runs').get()!.status,'halted',change);assert.equal(f.db.prepare('SELECT COUNT(*) AS count FROM run_recoveries').get()!.count,0,change);
 }finally{f.db.close();}}});



test('114 document recovery dispatches bounded pages and preserves paid checkpoint identity',async()=>{const f=setup();try{
 f.db.prepare('UPDATE runs SET expected_count=114').run();for(let i=0;i<112;i++){const fingerprint=`extra-${i}`;f.db.prepare("INSERT INTO documents(run_id,fingerprint,tag,original_filename,status,input_key,input_hash,workflow_id) VALUES('run',?,?,'original','running',?,'hash',?)").run(fingerprint,fingerprint,`input-${i}`,`old-${i}`);f.statuses.set(`old-${i}`,'errored');}
 const first=await recoverRun(f.store,'run','owner',f.options);assert.equal(first.started,50);assert.equal(first.pending,63);const second=await dispatchRecovery(f.store,'run','owner',f.options);assert.equal(second.started,50);assert.equal(second.pending,13);const third=await dispatchRecovery(f.store,'run','owner',f.options);assert.equal(third.pending,0);assert.equal(f.created.length,113);assert.equal(new Set(f.created).size,113);assert.equal(f.db.prepare('SELECT COUNT(*) AS count FROM run_recoveries').get()!.count,1);
 }finally{f.db.close();}});
test('legacy exact infrastructure error is eligible; similar text and ordinary errors are not',async()=>{for(const message of ['Connection closed: this Durable Object instance is no longer active. Reconnect or retry the request.','inactive durable object','ordinary vendor failure']){const f=setup();try{f.db.prepare('UPDATE runs SET halt_json=?').run(JSON.stringify({code:'E_INTERNAL',message}));if(message.startsWith('Connection closed:'))assert.equal((await inspectRunRecovery(f.store,'run','owner')).documents.length,1);else await assert.rejects(()=>inspectRunRecovery(f.store,'run','owner'));assert.equal(f.created.length,0);}finally{f.db.close();}}});
test('plan identities are immutable and stale activation rolls back without dispatch',async()=>{const f=setup();try{await recoverRun(f.store,'run','owner',f.options);assert.throws(()=>f.db.prepare("UPDATE run_recoveries SET actor='other'").run());assert.throws(()=>f.db.prepare("UPDATE run_recovery_documents SET new_workflow_id='replacement'").run());assert.throws(()=>f.db.prepare("UPDATE run_recovery_documents SET state='pending'").run());assert.throws(()=>f.db.prepare('DELETE FROM run_recoveries').run());}finally{f.db.close();}
 const stale=setup();try{stale.options.assertReady=async()=>{stale.db.prepare("UPDATE runs SET status='closing'").run();};await assert.rejects(()=>recoverRun(stale.store,'run','owner',stale.options));assert.equal(stale.created.length,0);assert.equal(stale.db.prepare('SELECT COUNT(*) AS count FROM run_recoveries').get()!.count,0);assert.equal(stale.db.prepare("SELECT workflow_id FROM documents WHERE fingerprint='pending'").get()!.workflow_id,'old-pending');}finally{stale.db.close();}});
function partialPlan(f:ReturnType<typeof setup>){
 f.db.prepare("UPDATE runs SET expected_count=114,halt_json=?").run(JSON.stringify({code:'E_INTERNAL',message:'Durable Object reset because its code was updated.'}));
 f.db.prepare("UPDATE documents SET status='running'").run();
 for(let i=0;i<112;i++){const fingerprint=`extra-${String(i).padStart(3,'0')}`;f.db.prepare("INSERT INTO documents(run_id,fingerprint,tag,original_filename,status,input_key,input_hash,workflow_id) VALUES('run',?,?,'original','running',?,'hash',?)").run(fingerprint,fingerprint,`input-${i}`,`old-${i}`);}
 f.db.prepare("INSERT INTO run_recoveries VALUES('generation-1','run',1,'owner','then','{}')").run();
 const docs=f.db.prepare('SELECT fingerprint,workflow_id FROM documents ORDER BY fingerprint').all();
 const reserved:string[]=[];
 docs.forEach((doc,i)=>{const id=`reserved-${i}`;reserved.push(id);f.db.prepare("INSERT INTO run_recovery_documents(recovery_id,fingerprint,old_workflow_id,new_workflow_id,state) VALUES('generation-1',?,?,?,?)").run(doc.fingerprint!,doc.workflow_id!,id,i<67?'started':i===67?'dispatching':'pending');f.db.prepare('UPDATE documents SET workflow_id=? WHERE fingerprint=?').run(id,doc.fingerprint!);if(i<68)f.statuses.set(id,'errored');});
 // One existing paid row plus 112 independent completed calls: exactly 113 preserved.
 for(let i=0;i<112;i++){const fingerprint=docs[i]!.fingerprint;f.db.prepare("INSERT INTO artifacts(key,run_id,kind,contains_text,created_at,state) VALUES(?,'run','raw',0,'then','complete')").run(`paid-${i}`);f.db.prepare("INSERT INTO checkpoints(run_id,fingerprint,name,status,artifact_key,started_at) VALUES('run',?,'reader-http-1','complete',?,'then')").run(fingerprint!,`paid-${i}`);f.db.prepare("INSERT INTO vendor_calls(attempt_id,run_id,fingerprint,role,model_requested,latency_ms,raw_key,created_at,cost_nano) VALUES(?,'run',?,'reader','pin',1,?,'then','100')").run(`run-${fingerprint}-reader-1`,fingerprint!,`paid-${i}`);}
 return reserved;
}
function supersedePlan(f:ReturnType<typeof setup>,prior='generation-1'){
 f.db.prepare("INSERT INTO run_recoveries VALUES('generation-2','run',2,'owner','later','{}')").run();
 f.db.prepare("INSERT INTO run_recovery_documents(recovery_id,fingerprint,old_workflow_id,new_workflow_id) SELECT 'generation-2',fingerprint,new_workflow_id,'next-'||fingerprint FROM run_recovery_documents WHERE recovery_id=?").run(prior);
 f.db.prepare("UPDATE documents SET workflow_id='next-'||fingerprint WHERE status!='complete'").run();
}
test('67 started, one uncertain terminal start, and 46 never-dispatched reservations can continue safely',async()=>{const f=setup();try{
 const reserved=partialPlan(f),calls=f.db.prepare('SELECT * FROM vendor_calls ORDER BY attempt_id').all(),checkpoints=f.db.prepare('SELECT * FROM checkpoints ORDER BY fingerprint,name').all(),artifacts=f.db.prepare('SELECT * FROM artifacts ORDER BY key').all();
 assert.equal(canOfferRecovery(await f.store.run('run')),true);
 const inspected=await inspectRunRecovery(f.store,'run','owner');assert.equal(inspected.documents.length,114);assert.equal(f.lookups.length,68);assert.ok(reserved.slice(68).every(id=>!f.lookups.includes(id)));assert.equal(f.created.length,0);
 const first=await recoverRun(f.store,'run','owner',f.options);assert.equal(first.generation,2);assert.equal(first.started,50);assert.equal(first.pending,64);await dispatchRecovery(f.store,'run','owner',f.options);const last=await dispatchRecovery(f.store,'run','owner',f.options);assert.equal(last.pending,0);assert.equal(f.created.length,114);assert.equal(new Set(f.created).size,114);assert.ok(f.created.every(id=>!reserved.includes(id)));assert.ok(reserved.slice(68).every(id=>!f.lookups.includes(id)));
 assert.deepEqual(f.db.prepare('SELECT * FROM vendor_calls ORDER BY attempt_id').all(),calls);assert.deepEqual(f.db.prepare('SELECT * FROM checkpoints ORDER BY fingerprint,name').all(),checkpoints);assert.deepEqual(f.db.prepare('SELECT * FROM artifacts ORDER BY key').all(),artifacts);assert.equal(f.db.prepare('SELECT COUNT(*) AS n FROM vendor_calls').get()!.n,113);
 assert.equal(f.db.prepare("SELECT COUNT(*) AS n FROM run_recovery_documents WHERE recovery_id='generation-1' AND state='pending'").get()!.n,46);
 }finally{f.db.close();}});
test('reserved pending proof requires exact current document pointer; uncertain starts never count as pending',async()=>{for(const mode of ['pointer-mismatch','unverified-dispatch','live-dispatch']){const f=setup();try{const reserved=partialPlan(f);if(mode==='pointer-mismatch')f.db.prepare("UPDATE documents SET workflow_id='unexpected' WHERE workflow_id=?").run(reserved[68]!);if(mode==='unverified-dispatch')f.statuses.delete(reserved[67]!);if(mode==='live-dispatch')f.statuses.set(reserved[67]!,'running');await assert.rejects(()=>recoverRun(f.store,'run','owner',f.options));assert.equal(f.created.length,0);assert.equal(f.db.prepare('SELECT COUNT(*) AS n FROM run_recoveries').get()!.n,1);}finally{f.db.close();}}});
test('known transient status resets retry reads only, bounded at three; arbitrary failures do not retry',async()=>{for(const [message,count,succeeds] of [['Durable Object reset because its code was updated.',2,true],['Connection closed: this Durable Object instance is no longer active. Reconnect or retry the request.',3,false],['unknown storage fault',1,false]] as const){const f=setup();try{f.db.prepare("UPDATE documents SET workflow_id=NULL WHERE fingerprint='finished'").run();for(let i=0;i<count;i++)f.lookupErrors.push(new Error(message));if(succeeds)await inspectRunRecovery(f.store,'run','owner');else await assert.rejects(()=>inspectRunRecovery(f.store,'run','owner'));assert.equal(f.lookups.length,succeeds?count+1:count);assert.equal(f.created.length,0);}finally{f.db.close();}}});
test('lost create acknowledgement plus transient status reset reconciles the exact reserved ID once',async()=>{const f=setup();try{f.loseAck();let checks=0;f.options.assertReady=async()=>{if(++checks===3)f.lookupErrors.push(new Error('Durable Object reset because its code was updated.'));};await recoverRun(f.store,'run','owner',f.options);assert.equal(f.created.length,1);assert.equal(f.lookups.filter(id=>id===f.created[0]).length,2);}finally{f.db.close();}});
test('a controller awaiting readiness cannot claim a pending item after another generation activates',async()=>{const f=setup();try{partialPlan(f);f.db.prepare("UPDATE runs SET status='running'").run();let checks=0;f.options.assertReady=async()=>{if(++checks===2)supersedePlan(f);};await assert.rejects(()=>dispatchRecovery(f.store,'run','owner',f.options));assert.equal(f.created.length,0);assert.equal(f.lookups.length,0);assert.equal(f.db.prepare("SELECT COUNT(*) AS n FROM run_recovery_documents WHERE recovery_id='generation-1' AND state='pending'").get()!.n,46);}finally{f.db.close();}});
test('a controller awaiting readiness cannot dispatch after the run halts',async()=>{const f=setup();try{partialPlan(f);f.db.prepare("UPDATE runs SET status='running'").run();let checks=0;f.options.assertReady=async()=>{if(++checks===2)f.db.prepare("UPDATE runs SET status='halted'").run();};await assert.rejects(()=>dispatchRecovery(f.store,'run','owner',f.options));assert.equal(f.created.length,0);assert.equal(f.lookups.length,0);}finally{f.db.close();}});
test('an old acknowledged create cannot mark dispatch started after a new generation activates',async()=>{const f=setup();try{const create=f.store.env.DOCUMENT_WORKFLOW.create.bind(f.store.env.DOCUMENT_WORKFLOW);f.store.env.DOCUMENT_WORKFLOW.create=async options=>{const result=await create(options);f.statuses.set(options!.id!,'errored');const plan=f.db.prepare('SELECT id FROM run_recoveries').get()!;supersedePlan(f,String(plan.id));return result;};await assert.rejects(()=>recoverRun(f.store,'run','owner',f.options));assert.equal(f.created.length,1);assert.equal(f.db.prepare('SELECT state FROM run_recovery_documents WHERE new_workflow_id=?').get(f.created[0]!)!.state,'dispatching');assert.equal(f.db.prepare("SELECT workflow_id FROM documents WHERE fingerprint='pending'").get()!.workflow_id,'next-pending');}finally{f.db.close();}});
test('D1 fences a legacy controller claim without relying on new application code',()=>{for(const mode of ['halted','superseded','pointer-mismatch','current']){const f=setup();try{const ids=partialPlan(f);if(mode!=='halted')f.db.prepare("UPDATE runs SET status='running'").run();if(mode==='superseded')supersedePlan(f);if(mode==='pointer-mismatch')f.db.prepare("UPDATE documents SET workflow_id='unexpected' WHERE workflow_id=?").run(ids[68]!);const claim=()=>f.db.prepare("UPDATE run_recovery_documents SET state='dispatching' WHERE new_workflow_id=? AND state='pending'").run(ids[68]!);if(mode==='current')assert.equal(claim().changes,1);else{assert.throws(claim,/reservation is no longer active/);assert.equal(f.db.prepare('SELECT state FROM run_recovery_documents WHERE new_workflow_id=?').get(ids[68]!)!.state,'pending');}}finally{f.db.close();}}});
test('activation cannot reuse an inspection from a superseded generation',async()=>{const f=setup();try{partialPlan(f);f.options.assertReady=async()=>{supersedePlan(f);};await assert.rejects(()=>recoverRun(f.store,'run','owner',f.options));assert.equal(f.created.length,0);assert.equal(f.db.prepare('SELECT COUNT(*) AS n FROM run_recoveries').get()!.n,2);assert.equal(f.db.prepare("SELECT COUNT(*) AS n FROM run_recovery_documents WHERE recovery_id='generation-1' AND state='pending'").get()!.n,46);}finally{f.db.close();}});
