import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync,type SQLInputValue} from 'node:sqlite';
import {readFileSync} from 'node:fs';
import {Store} from './store.ts';
import {recoverRun,inspectRunRecovery,dispatchRecovery} from './run-recovery.ts';
function setup(){
 const db=new DatabaseSync(':memory:');for(const file of ['0001_initial.sql','0003_extraction_metadata.sql','0008_run_recovery.sql'])db.exec(readFileSync('migrations/'+file,'utf8'));
 db.prepare('INSERT INTO quotes VALUES(?,?,?,?,?,?,?,?)').run('q','owner','then','interactive','types','hash','{}','{}');
 db.prepare("INSERT INTO runs(id,actor,status,created_at,mode,expected_count,threshold,threshold_justification,type_version,pack_json,budget_json,quote_id,halt_json) VALUES('run','owner','halted','then','interactive',2,.9,'original','types','frozen','budget','q',?)").run(JSON.stringify({code:'E_WORKFLOW_INTERRUPTED'}));
 for(const [fingerprint,status] of [['finished','complete'],['pending','running']])db.prepare('INSERT INTO documents(run_id,fingerprint,tag,original_filename,status,input_key,input_hash,workflow_id) VALUES(?,?,?,?,?,?,?,?)').run('run',fingerprint,fingerprint,'original',status,`input-${fingerprint}`,'hash',`old-${fingerprint}`);
 db.prepare("INSERT INTO artifacts(key,run_id,kind,contains_text,created_at,state) VALUES('paid','run','raw',0,'then','complete')").run();
 db.prepare("INSERT INTO checkpoints(run_id,fingerprint,name,status,artifact_key,started_at) VALUES('run','pending','confidence-http-1','complete','paid','then')").run();
 db.prepare("INSERT INTO vendor_calls(attempt_id,run_id,fingerprint,role,model_requested,latency_ms,raw_key,created_at,cost_nano) VALUES('run-pending-confidence-1','run','pending','confidence','pin',1,'paid','then','100')").run();
 const statuses=new Map([['old-finished','complete'],['old-pending','errored']]);const created:string[]=[];let loseAck=false,lookupFails=false;
 const prepare=(sql:string)=>{let args:SQLInputValue[]=[];return{bind(...values:SQLInputValue[]){args=values;return this;},async first(){return db.prepare(sql).get(...args)??null;},async all(){return{results:db.prepare(sql).all(...args)};},async run(){return{meta:{changes:Number(db.prepare(sql).run(...args).changes)}};}};};
 const env={DB:{prepare,async batch(statements:Array<{run():Promise<unknown>}>){db.exec('BEGIN');try{const result=[];for(const statement of statements)result.push(await statement.run());db.exec('COMMIT');return result;}catch(error){db.exec('ROLLBACK');throw error;}}},ARTIFACTS:{head:async()=>({})},DOCUMENT_WORKFLOW:{async get(id:string){return{async status(){if(lookupFails||!statuses.has(id))throw new Error('unverified');return{status:statuses.get(id)};}};},async create(options:{id:string}){created.push(options.id);statuses.set(options.id,'queued');if(loseAck)throw new Error('lost acknowledgement');}}} as unknown as Env;
 return{db,store:new Store(env),statuses,created,options:{acknowledged:true,assertReady:async()=>{}},loseAck:()=>{loseAck=true;},lookupFails:()=>{lookupFails=true;}};
}
test('explicit recovery keeps frozen run, paid checkpoints and old execution history; skips completed documents',async()=>{const f=setup();try{const checkpoint=f.db.prepare('SELECT * FROM checkpoints').all();const result=await recoverRun(f.store,'run','owner',f.options);assert.equal(result.pending,0);assert.equal(f.created.length,1);assert.equal(f.db.prepare("SELECT workflow_id FROM documents WHERE fingerprint='finished'").get()!.workflow_id,'old-finished');assert.deepEqual(f.db.prepare('SELECT * FROM checkpoints').all(),checkpoint);assert.equal(f.db.prepare('SELECT pack_json FROM runs').get()!.pack_json,'frozen');assert.equal(f.statuses.get('old-pending'),'errored');await dispatchRecovery(f.store,'run','owner',f.options);assert.equal(f.created.length,1);}finally{f.db.close();}});
test('lost creation acknowledgement reconciles reserved identity without another create',async()=>{const f=setup();try{f.loseAck();await recoverRun(f.store,'run','owner',f.options);await recoverRun(f.store,'run','owner',f.options);assert.equal(f.created.length,1);}finally{f.db.close();}});
test('unsafe state and unauthorized callers never dispatch or activate',async()=>{for(const change of ['owner','ack','ready','running-checkpoint','failed-checkpoint','writing','nonterminal','unknown-status','missing-input','batch','unknown-cost']){const f=setup();try{
 let actor='owner';if(change==='owner')actor='other';if(change==='ack')f.options.acknowledged=false;if(change==='ready')f.options.assertReady=async()=>{throw new Error('kill or budget blocked');};
 if(change==='running-checkpoint'||change==='failed-checkpoint')f.db.prepare('UPDATE checkpoints SET status=?').run(change.split('-')[0]);
 if(change==='writing')f.db.prepare("UPDATE artifacts SET state='writing'").run();if(change==='nonterminal')f.statuses.set('old-pending','waiting');if(change==='unknown-status')f.lookupFails();if(change==='missing-input')f.db.prepare("UPDATE documents SET input_key=NULL WHERE fingerprint='pending'").run();
 if(change==='batch')f.db.prepare("INSERT INTO batch_jobs(id,run_id,fingerprint,schema_attempt,state) VALUES('b','run','pending',1,'submitted')").run();
 if(change==='unknown-cost')f.db.prepare("INSERT INTO vendor_calls(attempt_id,run_id,fingerprint,role,model_requested,latency_ms,raw_key,created_at) VALUES('attempt','run','pending','confidence','pin',1,'paid','then')").run();
 await assert.rejects(()=>recoverRun(f.store,'run',actor,f.options),change);assert.equal(f.created.length,0,change);assert.equal(f.db.prepare('SELECT status FROM runs').get()!.status,'halted',change);assert.equal(f.db.prepare('SELECT COUNT(*) AS count FROM run_recoveries').get()!.count,0,change);
 }finally{f.db.close();}}});



test('114 document recovery dispatches bounded pages and preserves paid checkpoint identity',async()=>{const f=setup();try{
 f.db.prepare('UPDATE runs SET expected_count=114').run();for(let i=0;i<112;i++){const fingerprint=`extra-${i}`;f.db.prepare("INSERT INTO documents(run_id,fingerprint,tag,original_filename,status,input_key,input_hash,workflow_id) VALUES('run',?,?,'original','running',?,'hash',?)").run(fingerprint,fingerprint,`input-${i}`,`old-${i}`);f.statuses.set(`old-${i}`,'errored');}
 const first=await recoverRun(f.store,'run','owner',f.options);assert.equal(first.started,50);assert.equal(first.pending,63);const second=await dispatchRecovery(f.store,'run','owner',f.options);assert.equal(second.started,50);assert.equal(second.pending,13);const third=await dispatchRecovery(f.store,'run','owner',f.options);assert.equal(third.pending,0);assert.equal(f.created.length,113);assert.equal(new Set(f.created).size,113);assert.equal(f.db.prepare('SELECT COUNT(*) AS count FROM run_recoveries').get()!.count,1);
 }finally{f.db.close();}});
test('legacy exact infrastructure error is eligible; similar text and ordinary errors are not',async()=>{for(const message of ['Connection closed: this Durable Object instance is no longer active. Reconnect or retry the request.','inactive durable object','ordinary vendor failure']){const f=setup();try{f.db.prepare('UPDATE runs SET halt_json=?').run(JSON.stringify({code:'E_INTERNAL',message}));if(message.startsWith('Connection closed:'))assert.equal((await inspectRunRecovery(f.store,'run','owner')).documents.length,1);else await assert.rejects(()=>inspectRunRecovery(f.store,'run','owner'));assert.equal(f.created.length,0);}finally{f.db.close();}}});
test('plan identities are immutable and stale activation rolls back without dispatch',async()=>{const f=setup();try{await recoverRun(f.store,'run','owner',f.options);assert.throws(()=>f.db.prepare("UPDATE run_recoveries SET actor='other'").run());assert.throws(()=>f.db.prepare("UPDATE run_recovery_documents SET new_workflow_id='replacement'").run());assert.throws(()=>f.db.prepare("UPDATE run_recovery_documents SET state='pending'").run());assert.throws(()=>f.db.prepare('DELETE FROM run_recoveries').run());}finally{f.db.close();}
 const stale=setup();try{stale.options.assertReady=async()=>{stale.db.prepare("UPDATE runs SET status='closing'").run();};await assert.rejects(()=>recoverRun(stale.store,'run','owner',stale.options));assert.equal(stale.created.length,0);assert.equal(stale.db.prepare('SELECT COUNT(*) AS count FROM run_recoveries').get()!.count,0);assert.equal(stale.db.prepare("SELECT workflow_id FROM documents WHERE fingerprint='pending'").get()!.workflow_id,'old-pending');}finally{stale.db.close();}});
