export const builderCopy = {
  invalidName: 'A folder, filename, or tag is not a safe local name.',
  invalidTag: 'Every document must have a unique tag.',
  invalidFingerprint: 'A document fingerprint must be a full SHA-256 value.',
  locksMissing: 'This browser cannot lock the folder builder. Open the app in an up-to-date Chrome or Edge browser.',
  verifyFailed: 'The copied file does not match the original. Check the destination before resuming.',
  cancelled: 'The local folder scan was stopped.',
  invalidLimits: 'Enter the destination path and its path and filename limits before building.',
  longPath: 'A destination path is too long. Choose shorter naming or a shorter destination folder before writing.',
  conflict: 'A different file already exists at the destination. It has been kept unchanged.',
  sourceChanged: 'The source file has changed since its fingerprint was recorded. Nothing was copied.',
  sidecarConflict: 'A different decision note already exists. It has been kept unchanged.',
  reviewDecision: 'Choose the appropriate type folder and move this document there, or leave it for further review.',
  failureDecision: 'Resolve the reported problem, then explicitly start a new run for this document if needed.',
  summaryTitle: 'Local build summary',
  sidecarTitle: 'Document decision',
  originalFilename: 'Original filename',
  fingerprint: 'Fingerprint',
  tag: 'Tag',
  run: 'Run',
  rule: 'Decision rule',
  reasoning: 'Reasoning note',
  failureDetails: 'Reported failure',
  confidenceCheck: 'Confidence check',
  reader: 'Reader',
  decision: 'What to decide',
  missingVendor: 'No validated output is available. See the reasoning note.',
  complete: 'Every document and required decision note is present.',
  incomplete: 'The build needs attention. The entries below include every missing or unfinished file.',
  statuses: {
    copied: 'Copied',
    already_present: 'Already present with the same fingerprint',
    not_found: 'Not found in source folder',
    destination_conflict: 'Destination conflict',
    source_changed: 'Source changed',
    sidecar_conflict: 'Decision note conflict',
    write_failed: 'Could not finish this file',
    cancelled: 'Not attempted because the build was stopped',
  },
} as const;

