import test from 'node:test';import assert from 'node:assert/strict';import {mkdtempSync,writeFileSync,readFileSync,existsSync,rmSync} from 'node:fs';import {tmpdir} from 'node:os';import {join,dirname,resolve,basename} from 'node:path';
import {deriveWorkflowNames,withWorkflowDeployConfig,NEW_INSTALL_WORKFLOW_MARKER} from './workflow-install-name.mjs';
const config=()=>({name:'selected-worker',main:'core/server/worker.ts',assets:{directory:'dist'},alias:{'project-pack':'./projects/generic/project.json'},d1_databases:[{binding:'DB',migrations_dir:'migrations'}],vars:{MODEL_CALLS_ENABLED:'false'},workflows:[{binding:'DOCUMENT_WORKFLOW',name:NEW_INSTALL_WORKFLOW_MARKER,class_name:'DocumentWorkflow'}]});
test('new installation names are stable valid complete hashes of Worker and binding identity',()=>{const source=config(),result=deriveWorkflowNames(source);const name=result.config.workflows[0].name;assert.match(name,/^[a-f0-9]{64}$/);assert.equal(result.rewritten,true);assert.equal(name,deriveWorkflowNames(source).config.workflows[0].name);assert.notEqual(name,deriveWorkflowNames({...source,name:'another-worker'}).config.workflows[0].name);const other=config();other.workflows[0].binding='OTHER_WORKFLOW';assert.notEqual(name,deriveWorkflowNames(other).config.workflows[0].name);});
test('existing and customized names are preserved and input configuration never changes',()=>{const source=config(),before=structuredClone(source);deriveWorkflowNames(source);assert.deepEqual(source,before);for(const name of ['doc-classifier-generic-document','custom-workflow']){const existing=config();existing.workflows[0].name=name;const output=deriveWorkflowNames(existing);assert.equal(output.rewritten,false);assert.deepEqual(output.config,existing);}assert.equal(deriveWorkflowNames({name:'unrelated'}).rewritten,false);});
test('derivation fails loudly on missing Worker or binding identity and preserves all other fields',()=>{const source=config();for(const name of [null,'',' '])assert.throws(()=>deriveWorkflowNames({...source,name}));source.workflows[0].binding='';assert.throws(()=>deriveWorkflowNames(source));const result=deriveWorkflowNames(config()).config;result.workflows[0].name=NEW_INSTALL_WORKFLOW_MARKER;assert.deepEqual(result,config());});
test('generated config is beside source so relative paths retain their meaning and is cleaned after failure',()=>{const folder=mkdtempSync(join(tmpdir(),'workflow-config-'));const source=join(folder,'wrangler.jsonc');writeFileSync(source,JSON.stringify(config()));let generated;try{assert.throws(()=>withWorkflowDeployConfig(source,config(),path=>{generated=path;assert.equal(dirname(path),dirname(source));const value=JSON.parse(readFileSync(path,'utf8'));assert.equal(resolve(dirname(path),value.main),resolve(folder,config().main));assert.equal(resolve(dirname(path),value.assets.directory),resolve(folder,'dist'));assert.equal(resolve(dirname(path),value.alias['project-pack']),resolve(folder,'projects/generic/project.json'));assert.equal(resolve(dirname(path),value.d1_databases[0].migrations_dir),resolve(folder,'migrations'));assert.match(value.workflows[0].name,/^[a-f0-9]{64}$/);throw Error('command failed');}),/command failed/);assert.equal(existsSync(generated),false);assert.deepEqual(JSON.parse(readFileSync(source,'utf8')),config());}finally{assert.equal(dirname(resolve(folder)),resolve(tmpdir()));assert.ok(basename(folder).startsWith('workflow-config-'));rmSync(folder,{recursive:true,force:true});}});
test('existing deployment executes against its original configuration path without rewriting it',()=>{const source=resolve('wrangler.jsonc'),existing=config();existing.workflows[0].name='installed-workflow';assert.equal(withWorkflowDeployConfig(source,existing,path=>path),source);});

test('successful derived deployment returns its result and removes only the generated sibling config',()=>{const folder=mkdtempSync(join(tmpdir(),'workflow-config-')),source=join(folder,'wrangler.jsonc');writeFileSync(source,JSON.stringify(config()));let generated;try{const result=withWorkflowDeployConfig(source,config(),path=>{generated=path;assert.equal(existsSync(path),true);return 0;});assert.equal(result,0);assert.equal(existsSync(generated),false);assert.equal(existsSync(source),true);}finally{assert.equal(dirname(resolve(folder)),resolve(tmpdir()));assert.ok(basename(folder).startsWith('workflow-config-'));rmSync(folder,{recursive:true,force:true});}});
