export const uiCopy = {
  heroAction: 'Start with a folder', heroSecondary: 'See how it works', heroTrust: 'Your files. Your decisions.',
  processLabel: 'How a document finds its place', processInput: 'Your documents', processInputDetail: 'Text is extracted on your machine', processDecision: 'Agreement + certainty', processDecisionDetail: 'Rules determine the outcome', processResult: 'Organized folders. Clear exceptions.',
  workspaceTools: 'WORKSPACE', workspaceSupport: 'SUPPORT', stepLabel: 'Step',
  buildGuideTitle: 'Three selections. One organized folder.', buildGuideDetail: 'Use a completed run. Keep your original source folder unchanged, and choose a separate output folder.',
  buildResultsTitle: 'Select the results file', buildResultsDetail: 'Download this file from a completed run. It tells the app where each document belongs.',
  buildSourceTitle: 'Select your originals', buildSourceDetail: 'Choose the same source folder used for the run. These are the documents the app will copy.',
  buildDestinationTitle: 'Choose where the copies go', buildDestinationDetail: 'Choose a separate, empty output folder for the first build. Reuse it only to resume that build.',
  buildPathTitle: 'Check the destination path', buildAdvanced: 'Advanced filename and path settings', buildNext: 'After building: review the output folder, move any misplaced documents, then open Corrections.',
  selectionPending: 'Not selected yet', selectionReady: 'Selected', nextStep: 'Next step', openCorrections: 'Review folder corrections', openBuild: 'Create your local folders', openRun: 'Open run', startRun: 'Start a run',
  correctionGuideTitle: 'Review on your machine. Bring back the changes.',
  correctionGuideSteps: [
    {title:'Move documents',detail:'Open the output folder you built. Move each misplaced document into the right category folder. Keep its tagged filename unchanged.'},
    {title:'Select the whole output folder',detail:'Choose the results file for that run, then the output folder containing all category folders.'},
    {title:'Confirm what you checked',detail:'Tick only the folders whose documents you personally checked, then review the corrections below.'},
  ],
  correctionResultsTitle: '1. Select the results file for this run', correctionFolderTitle: '2. Select the corrected output folder', correctionCheckedHelp: 'A folder left unchecked is not treated as confirmation that its documents are correct.',
  correctionNothingFiled: 'No automatically filed documents were confirmed in this review. Folder moves are still recorded; this does not establish filing accuracy.',
  emptyRunsTitle: 'Your first run starts with a folder.', emptyRunsDetail: 'Choose documents on your machine, review the spending limits, and confirm. Progress and results will appear here.',
  readyDetail: 'The required configuration checks passed. Review spending limits before starting a run.', healthIntro: 'Check setup, spending activation, and the information this workspace retains.',
  setupTypeTitle: 'Define your document categories', setupTypeAction: 'The workspace has no usable category definitions yet. The person configuring this project needs to add names, descriptions, exclusions, and examples in the project repository, then deploy.',
  setupModelsTitle: 'Activate model calls when you are ready', setupModelsAction: 'Model calls are switched off. Finish defining your categories, then enable MODEL_CALLS_ENABLED in the deployment configuration. This permits paid calls; it does not start a run.',
  preflightReady: 'Extract a source folder, choose your spending limits, then select Review run.',

  signInSetupTitle: 'Choose who can use your document workspace.',
  signInSetupLede: 'Your app is deployed. Enable sign-in before anyone can open documents or start a run.',
  signInSetupHeading: 'Enable sign-in in Cloudflare',
  signInSetupDetail: 'The person who deployed this app completes this once. Everyone else simply signs in to the website.',
  signInSetupSteps: [
    'Open Cloudflare and select this app under Workers & Pages.',
    'Open Access, choose Protect this Worker behind Access, then select All traffic.',
    'Choose the people who may sign in and select Apply Access.',
    'Return here and select Check sign-in to reload the app and sign in.',
  ],
  signInEnable: 'Enable sign-in', signInCheck: 'Check sign-in',
  signInSetupSafety: 'Document operations are locked until sign-in is enabled. Model calls stay disabled until you finish setup and approve activation.',
  signInSetupNoCodes: 'No application identifiers, keys, or code changes are needed for this step.',

  providerWaitOpenai:'OpenAI requested a pause. This run is waiting before sending another request.', providerWaitTypesafe:'TypeSafe requested a pause. This run is waiting before sending another request.',
  documentFilename:'Document', resultExplanation:'Outcome details',
  workspaceLabel:'DOCUMENT WORKSPACE', navigationLabel:'Workspace navigation', privacyFootnote:'Your originals stay on your machine.', workspaceEyebrow:'LESS SORTING. MORE CLARITY.', sourceEmptyTitle:'A folder is all you need to begin.', sourceEmptyBody:'Choose a folder to extract its text and structure locally. You review the run before anything is uploaded.', setupStatus:'Setup needs attention', operationalStatus:'Ready for a new run', systemStatus:'System status',
  flowSteps:[{title:'Extract locally',detail:'Keep the originals on your machine.'},{title:'Review both opinions',detail:'See the evidence behind each outcome.'},{title:'Build and refine',detail:'Create folders and bring back corrections.'}],

  conditionalNotFor: (fromName:string,toName:string,toWhat:string) => 'Do not use "'+fromName+'" when "'+toName+'" is the closer fit under this definition: "'+toWhat+'".',
  proposalRetainedReader: 'Retained reader evidence', proposalReaderVerdict: 'Reader verdict', proposalQuoteProvenance: 'Quote provenance', proposalFrozenDefinitions: 'Frozen type definitions', proposalTypeVersion: 'Type version',
  proposalPartialContext: 'Full document context is unavailable here. Retained reader quotes are only partial evidence; review the original document before accepting an example.',

  evidenceOpen:'View recorded evidence', evidenceReload:'Refresh recorded evidence', evidenceConfidence:'Confidence check', evidenceReader:'Reader', evidenceChoice:'Selected type', evidenceCertainty:'Certainty', evidenceType:'Type', evidenceProbability:'Choice probability', evidenceNoul:'Independent yes/no probability', evidenceRationale:'Reason', evidenceQuotes:'Exact source quotes', evidenceAlternative:'Closest alternative', evidenceNone:'None', evidenceNoQuotes:'No evidence quotes were returned.', evidenceMissing:'No validated output has been recorded for this stage.', evidenceMismatch:'The evidence response does not match the selected document.',
  unrecognizedApiError: 'The server returned an unrecognized error response.',
  resultFiled:'Filed', resultReview:'Review', resultFailed:'Could not process', resultPriority:'Review first', resultPending:'Processing', resultUploaded:'Uploaded', resultQueued:'Queued', resultUnavailable:'Outcome unavailable', resultDetailsUnavailable:'Recorded details are unavailable.', resultDestination:'Destination', resultPriorityHeader:'Priority', resultRule:'Rule',
  resultReasons: { stage_failed: 'A processing stage could not finish. Review the recorded failure before retrying in a new run.', document_notes: 'The document needs a person to review its recorded notes.', agreement_at_threshold: 'Both systems agree at or above the run threshold.', low_certainty: 'Both systems agree, but certainty is below the run threshold.', straddles_types: 'The reader found more than one matching type.', possible_new_type: 'Neither system found a matching type. Consider whether a new type is needed.', systems_disagree: 'The two systems disagree. Review this document first.' },
  proposalReview: 'Proposals for Git review', proposalReviewHelp: 'Review these suggestions against the original documents. Accept or reject them in your project pack in Git, then deploy. Downloading does not change the taxonomy or threshold.',
  proposedExamples: 'Proposed examples', proposedExclusions: 'Proposed exclusions', proposedTypes: 'Proposed types', proposalDownload: 'Download suggestions',
  proposalType: 'Type', proposalEvidence: 'Evidence tags', proposalIdentifier: 'Suggested identifier', proposalIdentifierMissing: 'Choose an identifier in Git.',
  proposalIncompleteType: 'Complete the definition and exclusions in Git before deploying this type.', proposalNoExcerpt: 'No retained excerpt is available. Review the original document.',
  proposalNoExamples: 'No example candidates were proposed.', proposalNoExclusions: 'No exclusion candidates were proposed.', proposalNoTypes: 'No new types were proposed.',

  correctionManifestRequired: 'Choose the results file for this run before selecting the corrected output folder.',
  correctionTreeHelp: 'Choose the whole output folder containing the category folders, not an individual category folder.',
  correctionRescan: 'The run or results file changed. Choose the corrected output folder again before reviewing corrections.',
  vendorNoResponse: 'The latest inference attempt received no HTTP response.', vendorResponseFailed: 'The latest inference attempt received an unsuccessful HTTP response.', vendorResponseReceived: 'An HTTP success response was recorded. This alone does not establish a valid model result.',
  latestVendorAttempt: 'Latest recorded attempt', vendorRole: 'Role', vendorHttpStatus: 'HTTP status', vendorAttemptTime: 'Recorded at', vendorUnknownSpend: 'Calls with unknown spend', vendorRoleReader: 'Reader', vendorRoleConfidence: 'Confidence check', vendorRoleRecovery: 'Outline recovery',
  currentThreshold: 'Current threshold', thresholdJustification: 'Threshold justification', vendorStatus: 'Vendor status',
  healthUnavailable: 'Unavailable', vendorNotContacted: 'No inference calls have been recorded.',

  proposalContextUnavailable: 'Full document context is unavailable for some proposed examples. Any retained reader quotes are partial evidence. Review the original documents before accepting examples.',
  invalidTokenCount: 'A recorded token count is invalid. Stop this run and ask the technical contact to check the usage record.',
  invalidProjectCopy: 'Project copy contains a missing value, unknown or protected key, HTML, or prohibited wording. Correct the project pack in Git.',
  budgetTitle: 'Spending limits for this run', budgetMode: 'Budget choice', budgetLimited: 'Set spending limits', budgetUnlimited: 'Run without spending limits',
  budgetBlended: 'Blended \u00b7 both vendors', budgetOpenai: 'OpenAI', budgetTypesafe: 'TypeSafe', budgetUsd: 'Limit in USD', budgetHelp: 'Set at least one limit. You can combine an overall limit with separate vendor limits. An empty field leaves that category without its own limit.',
  budgetRequired: 'Enter at least one positive spending limit, or explicitly choose to run without spending limits.', invalidBudget: 'Enter a positive USD amount using up to 30 digits before the decimal point and up to nine decimal places.',
  unlimitedAcknowledgement: 'I understand that this run has no spending limit and may continue incurring charges.', unlimitedNeedsAcknowledgement: 'Acknowledge the no-limit warning before starting.',
  spendingLag: 'Spend is calculated from usage returned by vendor APIs. New calls stop when any limit is reached. Calls already in progress and submitted Batch work can still incur charges and exceed a limit; this is not a guaranteed billing cap.',
  spendUnavailable: 'Spend information is unavailable.', spendLimit: 'Limit', noCategoryLimit: 'No separate limit', noSpendingLimits: 'No spending limits',
  pendingAccounting: 'Vendor work awaiting final spend',
  knownSpend: 'Known spend subtotal', unaccountedSpend: 'Vendor calls with unaccounted spend',
  product: 'Document classification', browser: 'Use Chrome or Edge', browserReason: 'Your documents stay on your machine. Chrome and Edge provide the folder access needed to build and review your local tree.',
  nav: { home: 'Home', runs: 'Runs', build: 'Build folders', correct: 'Corrections', health: 'Health', help: 'How it works' },
  theme: 'Change colour theme', skip: 'Skip to content', loading: 'Loading…', refresh: 'Refresh', details: 'Technical details', retry: 'Try again',
  hero: 'Make sense of every document.', lede: 'Two independent systems review each document. A document is filed only when both agree with enough certainty and no blocking issues. Everything else comes back to you.',
  local: 'Choose your documents', localDetail: 'Only extracted text and structure are uploaded after you confirm a run.',
  outcomes: ['Filed · both systems agree above the threshold', 'Review · a person decides', 'Could not process · the reason is recorded'],
  setup: 'A few things before your first run', setupDetail: 'Your app is available, but processing stays locked until these setup steps are complete. Configuration changes currently need to be saved in the project repository and deployed.',
  newLocal: 'Start a new local extraction', localSession: 'Reselect the source folder to resume this local extraction. Previously failed documents remain recorded; use a new extraction to retry.',
  supportedFormats: 'Supported formats: PDF, Word (.docx), and PowerPoint (.pptx). Older .doc and .ppt files are unsupported.',
  chooseSource: 'Choose source folder', source: 'Source folder', extraction: 'Local extraction', files: 'Files', duration: 'Measured elapsed time', extracted: 'Extracted', failure: 'Could not process',
  alreadyConfirmed: 'This local extraction already has a confirmed run. Resume its upload, or explicitly start a new local extraction for another run.',
  duplicateContent: 'Duplicate document content was found. Review the source folder before creating a run; no file has been silently removed.',
  sourceSetChanged: 'Documents from this local run are missing from the selected folder. Reselect the original folder or explicitly start a new extraction.',
  extractionIncomplete: 'Local extraction is unfinished. Reselect the source folder to resume it.',
  quoteAction: 'Review run', override: 'Run anyway without a spending limit', overrideWarning: 'This run has no spending limit. Actual spend will be shown live and recorded, but nothing will stop the run on cost. The kill switch is the only way to halt it.',
  projectedDuration: 'Projected minimum at published limits', durationUnavailable: 'Unavailable because token counts or throughput limits are not known.', batchCapacityUnknown: 'The account Batch allowance is unknown. The provider will check capacity when this run is submitted.', batchDuration: 'Batch completion window', uploads: 'Text uploads completed', resumeUpload: 'Resume confirmed upload',
  preflight: 'Review and start', pendingEstimate: 'Set your spending limits before sending extracted text. Your original files stay on this machine.',
  mode: 'Run mode', interactive: 'Interactive', batch: 'Batch · completion window up to 24 hours', confirm: 'Confirm and start run', uploadUnavailable: 'Upload is unavailable until project configuration and the run submission service are ready.',
  estimateChanged: 'The project or run settings changed. Review the run and confirm again before starting.', batchCapacityExceeded: 'This batch exceeds the configured enqueued-token allowance. Choose interactive mode or start a smaller new run.',
  retryFailed: 'Retry failed documents in a new run', retryDetail: 'Choose the original source folder. Only matching failed documents are extracted into a new local session; new spending limits and your confirmation are required before any upload.',
  retryParent: 'Retry of run', retryMissing: 'Some retry originals are missing or changed. Choose the correct folder before reviewing the run; changed originals need an ordinary new extraction.', retryScope: 'The local retry scope contains unrelated or duplicate identities.',
  invalidRetry: 'The retry identity or parent-document listing is invalid.', excludedRetry: 'Outside this retry; not extracted', missingRetry: 'Not found with the original fingerprint',
  runs: 'Your runs', runsLede: 'Follow each run, inspect its decisions, and download the results when every document has an outcome.', noRuns: 'No runs have been recorded.', runId: 'Run', status: 'Status', progress: 'Documents completed', spend: 'Recorded spend', textHeld: 'Uploaded text is still held', textDeleted: 'Uploaded text has been deleted',
  download: 'Download results file and close run', close: 'Close run and delete uploaded text', kill: 'Halt all runs', killDetail: 'The kill switch stops subsequent work at the next step. Failed documents are never retried automatically.', noManifest: 'The results file is available after every document has an outcome.', documents: 'Documents', events: 'Recorded events',
  build: 'Turn results into real folders.', buildLede: 'Create organized copies on your machine. Your originals stay untouched, and existing files are never overwritten.', manifest: 'Choose results file', invalidManifest: 'This is not a supported results file. Choose the JSON results file downloaded from a completed run.', destination: 'Choose destination folder', destinationPath: 'Full destination folder path', pathHelp: 'The browser does not reveal the full path. Enter it so the builder can check path lengths before copying.', maxPath: 'Maximum path length', maxName: 'Maximum filename length', naming: 'Filename style', original: 'Tag and original filename', short: 'Tag and extension', buildAction: 'Build folders', stop: 'Stop after current file', buildComplete: 'Every document and required decision note is present.', buildIncomplete: 'The build needs attention. See each result and the summary saved in the destination.',
  unknownFolder: 'New type, or ignore these?', chooseDecision: 'Choose a decision', newType: 'Propose a new type', ignoreFolder: 'Ignore these files',
  from: 'Previous folder', to: 'Corrected folder',
  filedCount: (wrong:number, checked:number) => String(wrong)+' of '+String(checked)+' filed documents were wrong.',
  raiseSentence: (threshold:number, correct:number) => 'Raising the threshold to '+String(threshold)+' would have sent them to review and '+String(correct)+' correct ones too.',
  lowerSentence: (threshold:number, labels:number, errors:number) => 'Lowering the threshold to '+String(threshold)+' would have filed '+String(labels)+' of these automatically with '+String(errors)+' errors.',
  cannotSeparate: 'The threshold cannot separate these. Review the affected documents and their type definitions.',
  correctionSummary: (newTypes:number, unmatched:number, deleted:number) => String(newTypes)+' proposed types; '+String(unmatched)+' unmatched files; '+String(deleted)+' missing files excluded.',
  correct: 'Your judgment makes the difference.', correctLede: 'Move documents into the right folders, then show the app what changed. Nothing is applied to future runs without approval.', tree: 'Choose corrected output folder', checked: 'Which folders did you check?', analyze: 'Review corrections', correctionRun: 'Run identifier', listing: 'Documents in the corrected folder', apply: 'Apply this threshold', noAutomatic: 'Suggestions never change the project on their own. Type changes are reviewed and committed in Git.',
  health: 'Check your workspace.', ready: 'READY', notReady: 'NOT READY', blockers: 'What needs attention', versions: 'Versions and project configuration', callsEnabled: 'Model calls are enabled', callsDisabled: 'Model calls are disabled', heldRuns: 'Runs still holding uploaded text', project: 'Project configuration · read only',
  error: 'This action could not finish.', errorAction: 'Check the details below and retry when the problem is resolved.', requestFailed: 'The server rejected the request.', sourceScan: 'Reading fingerprints locally', chooseFirst: 'Choose the required files and folders first.', summary: 'Summary file', yes: 'Yes', no: 'No',
  helpTitle: 'Two opinions. One set of rules. Your decision when it matters.',
  helpSteps: [
    ['1. Read locally', 'Choose your source folder. The browser extracts text and structure and computes a content fingerprint. Original documents never leave your machine. Scanned documents are reported without OCR.'],
    ['2. Confirm the run', 'Choose overall or vendor spending limits, or explicitly acknowledge running without limits. Choose interactive or Batch processing. Nothing is uploaded before you confirm.'],
    ['3. Compare both systems', 'Both systems receive the full extracted text. The confidence check also receives the document structure. Nothing is shortened to fit a local token count. Deterministic rules place a document in its type folder only when both agree at or above the certainty threshold. Notes and disagreement go to review.'],
    ['4. Build your tree', 'Download the results file and select your originals and destination. The builder copies matching files, adds decision notes to review and failure folders, and records every missing or conflicting file.'],
    ['5. Correct and learn', 'Move files between folders, then identify which folders you checked. The system reports every move and proposes changes. Nothing is applied automatically.'],
  ],
  wrongTitle: 'When something goes wrong', wrongRows: [['A document cannot be read', 'Its reason appears in could_not_process. Others continue.'], ['The systems disagree', 'The document goes to human_review for your decision.'], ['A model pin, key or storage check fails', 'The affected run stops. Health shows the blocker and what to do.'], ['A source file is missing during building', 'It is listed as not found. Select the correct source and resume.']],
  faqTitle: 'Common questions', faq: [['When is uploaded text deleted?', 'Downloading the finished results file or explicitly closing a run deletes uploaded text and outline. Decisions, vendor outputs and fingerprints remain. Nothing is deleted on a timer.'], ['Will corrections change future results automatically?', 'No. Threshold changes require your explicit action. Definition and example changes are proposals for review in Git.'], ['Can I resume a build?', 'Yes. Files already present with the same fingerprint are skipped; conflicting files are left unchanged.'], ['Why Chrome or Edge?', 'Local folder access lets the app build your tree while keeping originals on your machine. Other browsers are not supported.']],
} as const;
